name: browser tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  browser:
    runs-on: ubuntu-latest

    name: Browser tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, sockets
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 20

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Install Playwright
        run: npm install

      - name: Execute browser tests
        run: composer test:browser

      - name: Upload failure screenshots
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: browser-screenshots
          path: tests/Browser/Screenshots
          if-no-files-found: ignore
